baseurl = "https://example.org/"
title = "SDAV Final Project"
theme = "creative portfolio"
languageCode = "en-us"
disqusShortname = ""
googleAnalytics = ""
themesDir = "themes"
baseURL = ""
publishDir = "public"
picture  = "static/img/portfolio/business-card-26.jpg"

[params]
style = "default"
description = "Describe your website"
copyright = "&copy;2021 Social Data Analaysis and Viz DTU"
sidebarAbout = [
  "<p><strong>Hereby we analyze the socio-economical impact of covid 19 cases in London and give an overview of the main trends and aspects.</strong></p>",
"We created some visualizations that, paired with text, will highlight the main facts we found out analyzing the London Government data. ",
"The focus is on interactive visualization. This will help a user to higlight easilly the factors he is more interested into.",
"Informations we report here are about Cases (between march 2019 and May 2021), vaccinations, retail activities and mobility in the city. The notebook link to GitHub of project is at the bottom left."
]
email = "you@yoursite.com"

  [[params.navlinks]]
  image = "interface/LondonCOVTitle.png"

  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  github = "full profile url in github"