baseurl = "https://example.org/"
title = "SDAV Final Project"
theme = "creative portfolio"
languageCode = "en-us"
disqusShortname = ""
googleAnalytics = ""
themesDir = "themes"
baseURL = ""
publishDir = "public"
picture  = "static/img/portfolio/business-card-26.jpg"

[params]
style = "default3"
description = "Describe your website"
copyright = "&copy;2016 Your name or company"
sidebarAbout = [
  "We are here to have fun",
  "Originally from La Cava, currently based yet in La Cava due to COVID."
]
email = "you@yoursite.com"

  [[params.navlinks]]
  image = "interface/LondonCOVTitle.png"

  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  github = "full profile url in github"
