baseurl = "https://example.org/"
title = "Creative portfolio"
theme = "creative portfolio"
languageCode = "en-us"
disqusShortname = ""
googleAnalytics = ""
themesDir = "themes"
baseURL = ""
publishDir = "public"

[params]
style = "default"
description = "Describe your website"
copyright = "&copy;2016 Your name or company"
sidebarAbout = [
  "We are here to have fun",
  "Originally from Toronto, currently based khgjck London."
]
email = "you@yoursite.com"

  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook = "full page or profile url in facebook"
  googleplus = "full profile url in googleplus"
  email = "email@example.com"
  twitter = "full profile url in twitter"
  linkedin = "full profile url in linkedin"
  stackoverflow = "full profile url in stackoverflow"
  instagram = "full profile url in instagram"
  github = "full profile url in github"
  gitlab = "full profile url in gitlab"
  youtube = "full profile url in youtube"
  whatsapp = "wa.me service link"
