baseurl = "https://example.org/"
title = "SDAV Final Project"
theme = "creative portfolio"
languageCode = "en-us"
disqusShortname = ""
googleAnalytics = ""
themesDir = "themes"
baseURL = ""
publishDir = "public"
picture  = "static/img/portfolio/business-card-26.jpg"

[params]
style = "default"
description = "Describe your website"
copyright = "&copy;2021 Social Data Analaysis and Viz DTU"
sidebarAbout = [
  "<p><strong>Hereby we analyze the socio-economical impact of covid 19 cases in London and give an overview of the main trends and aspects.</strong></p>",
"Selected visualizations (to see all check notebook) paired with their descriptive text highlight the main facts found on the analysis of <a href="https://data.london.gov.uk/dataset/coronavirus-covid-19-mobility-report"> [London Government] data. ",
"The focus is on interactive visualization. This help the user to higlight easilly the factors he is more interested into.",
"The reported here are about Cases (between march 2019 and May 2021), vaccinations, retail activities and mobility in the city.",
"<strong>The notebook link to the project's GitHub is at the bottom left part icon.</strong>"

]
email = "you@yoursite.com"

  [[params.navlinks]]
  image = "interface/LondonCOVTitle.png"

  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  github = "full profile url in github"