baseurl = "https://example.org/"
title = "SDAV Final Project"
theme = "creative portfolio"
languageCode = "en-us"
disqusShortname = ""
googleAnalytics = ""
themesDir = "themes"
baseURL = ""
publishDir = "public"

[params]
style = "default"
description = "Describe your website"
copyright = "&copy;2016 Your name or company"
sidebarAbout = [
  "We are here to have fun",
  "Originally from Toronto, currently bazsed in London."
]
email = "you@yoursite.com"s

  [[params.navlinks]]
  image = "img/interface/LondonCOVTitle.png"

  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  github = "full profile url in github"
